repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: requirements-txt-fixer
      - id: trailing-whitespace
        exclude: ^(data|patches)/.*$
      - id: end-of-file-fixer
        exclude: ^(data|patches)/.*$
      - id: check-yaml
        exclude: ^data/

  - repo: https://github.com/psf/black
    rev: 24.10.0  # Use the latest stable version
    hooks:
      - id: black
        args: [--line-length=88]
