name: Continuous Integration

on:
  pull_request:
    branches: [main]

  push:
    branches: [main]
    tags: [v*]

env:
  PYTHON_VERSION: "3.11"
  BUILD_TYPE: Release

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install style checkers
        run: pip install --user cpplint cppcheck clang-format==20.1.4

      - name: Cache pre-commit
        uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: ${{ runner.os }}-pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pre-commit-

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1

  build-and-test:
    needs: pre-commit
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macOS-latest]
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: "pip"

      - name: Install Python dependencies
        run: |
          pip install numpy pytest 'pyharp>=1.7.1' 'torch==2.7.1'
